---
- name: Fedora system-wide customizations
  hosts: localhost
  become: yes
  become_method: sudo
  tasks:
    - name: Install software from official repos
      dnf: state=present name={{ item }}
      with_items:
      - brasero
      - chromium
      - cpio
      - curl
      - docker
      - git
      - gnome-tweak-tool
      - keepassx
      - kernel-devel
      - kernel-headers
      - libselinux-python
      - lsof
      - nmap
      - numix-gtk-theme
      - numix-icon-theme
      - numix-icon-theme-circle
      - python2
      - python2-dnf
      - python2-flake8
      - python2-tox
      - python2-virtualenv
      - sed
      - sysstat
      - tar
      - unzip
      - vim
      - wget
      - zip

    - name: Remove unwanted software
      dnf: state=absent name={{ item }}
      with_items:
      - evolution
      - rhythmbox
      - firefox

    - name: Update all software
      dnf: state=latest name=*

    - name: Service sshd is enabled and started
      service: name=sshd enabled=yes state=started

    - name: Service firewalld is enabled and started
      service: name=firewalld enabled=yes state=started

 #   - name: Enable official VirtualBox repo
 #     get_url:
 #       url: http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
 #       dest: /etc/yum.repos.d/virtualbox.repo
 #       mode: 0644

    - name: Download GPG keys from RPM Fusion free
      get_url:
        url: http://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_version }}
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_version }}
        mode: 0644

    - name: Download GPG keys from RPM Fusion nonfree
      get_url:
        url: http://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ ansible_distribution_version }}
        dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ ansible_distribution_version }}
        mode: 0644

    - name: Enable RPM Fusion free
      yum_repository:
        name: rpmfusion-free
        description: RPM Fusion for Fedora $releasever - Free
        baseurl: http://download1.rpmfusion.org/free/fedora/releases/$releasever/Everything/$basearch/os/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-$releasever&arch=$basearch
        enabled: 1
        metadata_expire: 14d
        gpgcheck: 1
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever

    - name: Enable RPM Fusion free updates
      yum_repository:
        name: rpmfusion-free-updates
        description: RPM Fusion for Fedora $releasever - Free - Updates
        baseurl: http://download1.rpmfusion.org/free/fedora/updates/$releasever/$basearch/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=free-fedora-updates-released-$releasever&arch=$basearch
        enabled: 1
        gpgcheck: 1
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-free-fedora-$releasever

    - name: Enable RPM Fusion nonfree
      yum_repository:
        name: rpmfusion-nonfree
        description: RPM Fusion for Fedora $releasever - Nonfree
        baseurl: http://download1.rpmfusion.org/nonfree/fedora/releases/$releasever/Everything/$basearch/os/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-$releasever&arch=$basearch
        enabled: 1
        metadata_expire: 14d
        gpgcheck: 1
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever

    - name: Enable RPM Fusion nonfree updates
      yum_repository:
        name: rpmfusion-nonfree-updates
        description: RPM Fusion for Fedora $releasever - Nonfree - Updates
        baseurl: http://download1.rpmfusion.org/nonfree/fedora/updates/$releasever/$basearch/
        metalink: https://mirrors.rpmfusion.org/metalink?repo=nonfree-fedora-updates-released-$releasever&arch=$basearch
        enabled: 1
        gpgcheck: 1
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-fedora-$releasever

    - name: Install software from unofficial repos
      dnf: state=present name={{ item }}
      with_items:
      - vlc
      - VirtualBox

    - name: Download Atom Editor from GitHub
      get_url:
        url: https://atom.io/download/rpm
        dest: /tmp/atom.x86_64.rpm
        force: no
        mode: 0755

    - name: Install Atom Editor
      dnf: name=/tmp/atom.x86_64.rpm state=present

- name: Fedora user customizations
  hosts: localhost
  become: no
  tasks:
    - name: Setting the Numix GTK theme
      command: /usr/bin/gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"

    - name: Setting the Numix icon theme
      command: /usr/bin/gsettings set org.gnome.desktop.interface icon-theme "Numix-Circle-Light"

    - debug: msg="Use the command 'gsettings list-keys org.gnome.desktop.interface' to see more options"

    - debug: msg="Remember to download the VirtualBox Extension Pack from https://www.virtualbox.org/wiki/Downloads"
